version: '3.5'

services:

    # web
    web:
        container_name: ${COMPOSE_PROJECT_NAME}_web
        build: ./nginx
        ports:
            - "${WEB_HTTP_PORT}:80"
            - "${WEB_SSL_PORT}:443"
        volumes:
            - ../src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    # app
    app:
        container_name: ${COMPOSE_PROJECT_NAME}_app
        build:
            context: ./php-fpm
            args:
                - PHPFPM_VERSION=${PHPFPM_VERSION}
                - COMPOSER_VERSION=${COMPOSER_VERSION}
                - NODEJS_VERSION_MAJOR=${NODEJS_VERSION_MAJOR}
        volumes:
            - ../src:/var/www/html
        #networks:
            #- default

    # db
    db:
        container_name: ${COMPOSE_PROJECT_NAME}_db
        build:
            context: ./mariadb
            args:
                - MARIADB_VERSION=${MARIADB_VERSION}
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - db-store:/var/lib/mysql
            - ../doc/db:/doc/db
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}

    # mail
    mail:
        container_name: ${COMPOSE_PROJECT_NAME}_mail
        build: ./mailhog
        ports:
            - ${MAIL_SMTP_PORT}:1025
            - ${MAIL_WEB_PORT}:8025
        volumes:
            - mail-store:/tmp
        environment:
            MH_STORAGE: maildir
            MH_MAILDIR_PATH: /tmp

volumes:
    db-store:
        name: ${COMPOSE_PROJECT_NAME}_db_store
    mail-store:
        name: ${COMPOSE_PROJECT_NAME}_mail_store